name: Build and deploy Node.js app to Azure Web App - scougalrubber

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - name: Adjust standalone files
        run: |
          cp -r .next/static .next/standalone/.next/static
          cp -r public .next/standalone/public
      - name: Zip artifact for deployment
        run: zip release.zip .next/standalone node_modules package.json package-lock.json -r
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
    permissions:
      id-token: write
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Clean wwwroot folder
        run: |
          if [ -d wwwroot ]; then
            find wwwroot -mindepth 1 -delete
          else
            mkdir -p wwwroot
          fi
      - name: Unzip artifact for deployment
        run: unzip release.zip -d wwwroot
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D26ECE85B3F4D968A12714C66BE2624 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5035FD619AA74FFB926F308861E67391 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5FD29BC4236D4647A7EB76F5837B1B07 }}
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "scougalrubber"
          package: "./wwwroot"
